adding SimplyCyber to creators list.
ZetaTwo/security-creators pull request #42
Opened 2021-04-05 01:12 UTC by gerryguy311

per our email communication. adding simply cyber using the same format as other creators in the JSON.

2021-04-16 18:05 UTC, ZetaTwo requested changes
See comments

2021-04-16 18:05 UTC, ZetaTwo commented on src/assets/data/creators.json
> +   "schedule": "New Videos Every Monday at Noon EST Helping YOU Make and Take a Cybersecurity Care$
This seems to have been cut off.

2021-04-16 18:05 UTC, ZetaTwo commented on src/assets/data/creators.json
> +   "tags": ["Career", "Cybersecurity Awareness", "RED/BLUE TEAM", "Breaking into industry", "Mento$
This seems to have been cut off.

2021-04-16 18:05 UTC, ZetaTwo commented on src/assets/data/creators.json
> +   "schedule": "New Videos Every Monday at Noon EST Helping YOU Make and Take a Cybersecurity Care$
Also, please keep it short.

2021-04-19 16:26 UTC, gerryguy311 commented on src/assets/data/creators.json
> +   "schedule": "New Videos Every Monday at Noon EST Helping YOU Make and Take a Cybersecurity Care$
"schedule": "Monday 12:00 EST. Make and Take a Cyber Career Further, Faster"

2021-04-19 16:26 UTC, gerryguy311 commented on src/assets/data/creators.json
> +   "tags": ["Career", "Cybersecurity Awareness", "RED/BLUE TEAM", "Breaking into industry", "Mento$
"tags": ["Career", "Cybersecurity Awareness", "Soc Analyst", "Mentoring"]

2021-04-19 16:27 UTC, gerryguy311 commented
Provided replies to two text fields that were cutoff. Thanks again for the opportunity.

2021-04-19 19:25 UTC, merged