voiceofteluguethicalhacking joining request
ZetaTwo/security-creators pull request #65
Opened 2023-03-14 16:52 UTC by voiceofteluguethicalhacking

i have added all the required details as i mentioned in the email

2023-03-19 18:58 UTC, ZetaTwo commented on src/assets/data/creators.json
> +    "schedule": "Weekly uploads",
Why this change?

2023-03-22 21:53 UTC, ZetaTwo requested changes

2023-03-22 21:53 UTC, ZetaTwo commented on src/assets/data/creators.json
> +    "name": "Voiceofteluguethicalhacking",
You have added two copies. Please fix to only have one copy.

2023-03-23 04:33 UTC, closed without merging

2023-03-23 04:34 UTC, voiceofteluguethicalhacking commented
i will create a new pull request